# Generated by Django 4.2.2 on 2023-06-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esercizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AR', 'Arm'), ('AB', 'Abdomen'), ('L', 'Leg')], default='AR', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ripetizioni', models.IntegerField(default=0)),
                ('carico', models.TextField(choices=[('C10', '10 kg'), ('C20', '20 kg'), ('C30', '30 kg')], default='C10')),
            ],
        ),
        migrations.CreateModel(
            name='Scheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeScheda', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.scheda')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchedaAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.esercizi')),
                ('Scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.scheda')),
            ],
        ),
    ]
