# Generated by Django 4.2.2 on 2023-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_rename_asform_userassign_scheda'),
    ]

    operations = [
        migrations.AddField(
            model_name='esercizi',
            name='ExID',
            field=models.IntegerField(default=0),
        ),
    ]
